###
POST http://localhost:8080/products
Content-Type: application/json
X-Correlation-Id: yBauqKUWBKLt
X-Auth-Token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2MjY5NzUwNzAsInVzZXJfaWQiOiJhZG5pbnNpamF3YS5vZmZpY2VAZ21haWwuY29tIn0.mjm4yOzIG6I6ASXHEIm66prjkbVcfQbjtfrWl7fU5Sw

[
  {
    "name": "alexa",
    "price": 250,
    "currency": "INP",
    "vendor": "Amazon",
    "accessories": ["charger", "subscription", "gift coupon"]
  }
]
###
GET http://localhost:8080/products
X-Auth-Token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2MjY5NzUwNzAsInVzZXJfaWQiOiJhZG5pbnNpamF3YS5vZmZpY2VAZ21haWwuY29tIn0.mjm4yOzIG6I6ASXHEIm66prjkbVcfQbjtfrWl7fU5Sw
###
GET http://localhost:8080/products?_id=60f9786367f22c1cee842977
X-Auth-Token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2MjY5NzUwNzAsInVzZXJfaWQiOiJhZG5pbnNpamF3YS5vZmZpY2VAZ21haWwuY29tIn0.mjm4yOzIG6I6ASXHEIm66prjkbVcfQbjtfrWl7fU5Sw
###
GET http://localhost:8080/products/60f9786367f22c1cee842977
X-Auth-Token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2MjY5NzUwNzAsInVzZXJfaWQiOiJhZG5pbnNpamF3YS5vZmZpY2VAZ21haWwuY29tIn0.mjm4yOzIG6I6ASXHEIm66prjkbVcfQbjtfrWl7fU5Sw
###
PUT http://localhost:8080/products/60f9786367f22c1cee842977
X-Auth-Token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2MjY5NzUwNzAsInVzZXJfaWQiOiJhZG5pbnNpamF3YS5vZmZpY2VAZ21haWwuY29tIn0.mjm4yOzIG6I6ASXHEIm66prjkbVcfQbjtfrWl7fU5Sw
Content-Type: application/json
X-Correlation-Id: yBauqKUWBKLt

{
  "name": "alexa",
  "price": 250000,
  "currency": "INP",
  "discount": 50,
  "vendor": "Amazon",
  "accessories": ["charger", "subscription", "gift coupon"],
  "is_essential": false
}
###
PUT http://localhost:8080/products/60f9786367f22c1cee842977
X-Auth-Token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2MjY5NzUwNzAsInVzZXJfaWQiOiJhZG5pbnNpamF3YS5vZmZpY2VAZ21haWwuY29tIn0.mjm4yOzIG6I6ASXHEIm66prjkbVcfQbjtfrWl7fU5Sw
Content-Type: application/json
X-Correlation-Id: yBauqKUWBKLt

{
  "name": "alexas"
}
###
DELETE http://localhost:8080/products/60f9786367f22c1cee842977
X-Auth-Token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRob3JpemVkIjp0cnVlLCJleHAiOjE2MjY5NzUwNzAsInVzZXJfaWQiOiJhZG5pbnNpamF3YS5vZmZpY2VAZ21haWwuY29tIn0.mjm4yOzIG6I6ASXHEIm66prjkbVcfQbjtfrWl7fU5Sw
###
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "username": "adninsijawa.office@gmail.com",
  "password": "password"
}
###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "adninsijawa.office@gmail.com",
  "password": "password"
}
###