###
POST http://localhost:8080/products
Content-Type: application/json
X-Correlation-Id: yBauqKUWBKLt

[
  {
    "name": "alexa",
    "price": 250,
    "currency": "INP",
    "vendor": "Amazon",
    "accessories": ["charger", "subscription", "gift coupon"]
  }
]
###
GET http://localhost:8080/products
###
GET http://localhost:8080/products?_id=60f9786367f22c1cee842977
###
GET http://localhost:8080/products/60f9786367f22c1cee842977
###
PUT http://localhost:8080/products/60f9786367f22c1cee842977
Content-Type: application/json
X-Correlation-Id: yBauqKUWBKLt

{
  "name": "alexa",
  "price": 250000,
  "currency": "INP",
  "discount": 50,
  "vendor": "Amazon",
  "accessories": ["charger", "subscription", "gift coupon"],
  "is_essential": false
}
###
PUT http://localhost:8080/products/60f9786367f22c1cee842977
Content-Type: application/json
X-Correlation-Id: yBauqKUWBKLt

{
  "name": "alexas"
}
###
DELETE http://localhost:8080/products/60f9786367f22c1cee842977
###
POST http://localhost:8080/users
Content-Type: application/json

{
  "username": "adninsijawa.office@gmail.com",
  "password": "password"
}